default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: dgu 
  password: 

development:
  <<: *default
  database: tws_development

test:
  <<: *default
  database: tws_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
