default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: dgu 
  password: 

development:
  <<: *default
  database: tws_development

test:
  <<: *default
  database: tws_test

production:
  <<: *default
  database: tws_productio 
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASS'] %>
